# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: rust:latest
stages:
- test
- doc
sast:
  stage: test

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - target/

include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

test:cargo:
  stage: test
  script:
  - rustc --version && cargo --version
  - cargo test --workspace

pages:
  stage: doc
  script:
    - cargo doc --no-deps --release
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=./novaposhta/index.html">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main